# Generated by Django 4.0.2 on 2022-03-17 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voter',
            name='fName',
        ),
        migrations.RemoveField(
            model_name='voter',
            name='lName',
        ),
    ]
