# Generated by Django 4.0.2 on 2022-03-17 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_remove_voter_fname_remove_voter_lname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precinct',
            name='pNum',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
