# Generated by Django 4.0.2 on 2022-03-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0003_alter_precinct_pnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='has_voted',
            field=models.BooleanField(default=False, verbose_name='Voted'),
        ),
    ]
