# Generated by Django 4.0.2 on 2022-03-18 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_voter_has_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='contact',
            field=models.CharField(default='09000000000', max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{5}$')]),
        ),
    ]
