# Generated by Django 4.0.2 on 2022-03-30 14:23

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_voter_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faci',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rep',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('mName', models.CharField(max_length=100)),
                ('vId', models.CharField(max_length=100)),
                ('pNum', models.CharField(max_length=100)),
                ('Add', models.CharField(max_length=300)),
                ('has_voted', models.BooleanField(default=False, verbose_name='Voted')),
                ('contact', models.CharField(default='09000000000', max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$')])),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_faci',
            field=models.BooleanField(default=False, verbose_name='is facilitator'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_rep',
            field=models.BooleanField(default=False, verbose_name='is representative'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='contact',
            field=models.CharField(default='09000000000', max_length=11, validators=[django.core.validators.RegexValidator('^[0-9]{11}$')]),
        ),
    ]
